# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Zamanian Lab, University of Wisconsin-Madison
description: > # this means to ignore newlines until "baseurl:"
  Mostafa Zamanian, University of Wisconsin-Madison
  
  
baseurl: 
url: "http://www.zamanianlab.org" # the base hostname & protocol for your site

#sidebar
default-image:  # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.


# Build settings
markdown: kramdown
#paginate: 10
#permalink: /blog/:title/
#paginate_path: /blog/:num/

# Tracker
analytics: UA-90011510-1

# Sass style
sass:
  style: compressed

# Ruby Gems 
plugins: [jekyll-paginate, jekyll-seo-tag]

