# Site settings
title: Zamanian Lab, University of Wisconsin-Madison
email: 
url: https://zamanianlab.github.io
description: "Laboratory of Mostafa Zamanian, University of Wisconsin-Madison"

#Gems
gems:
  - jekyll-feed
  
# Color settings (hex-codes without the leading hash-tag)
color:
  primarybg: '#ffffff'
  links: '#219ab3'

# Footer settings
footer:  "Mostafa Zamanian"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/parazamanian
  #- title: facebook
  #  url:
  #- title: stack-overflow
  #  url: http://stackoverflow.com/questions/tagged/jekyll
  #- title: bitbucket
  #  url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/zamanianlab

# Build settings
markdown: kramdown
permalink: pretty
